export const WEAPONS=Object.freeze({
    SPEAR:'SPEAR',
    DAGGER:'DAGGER',
    SCIMITAR:'SCIMITAR',
    SWORD:'SWORD',

})
let WEAPONmap={}
//dmg dice d(amount)
WEAPONmap[WEAPONS.SPEAR]=8
WEAPONmap[WEAPONS.SCIMITAR]=10
WEAPONmap[WEAPONS.DAGGER]=4
WEAPONmap[WEAPONS.SWORD]=10
export {WEAPONmap};

export const ARMOUR=Object.freeze({
    LOIN_CLOTH:'LOIN_CLOTH',
    OXFORD_BLUE_ROBE:'OXFORD_BLUE_ROBE',
    CAMBRIDGE_BLUE_ROBE:'CAMBRIDGE_BLUE_ROBE',
    LABCOAT:'LABCOAT',
    PLATE:'PLATE',
    GANDALFS_WHITE_ROBES:'GANDALFS_WHITE_ROBES',
    CHAINMAIL:'CHAINMAIL',
})

let ARMOURmap={}
ARMOURmap[ARMOUR.LOIN_CLOTH]=10
ARMOURmap[ARMOUR.OXFORD_BLUE]=12
ARMOURmap[ARMOUR.CAMBRIDGE_BLUE]=14
ARMOURmap[ARMOUR.LABCOAT]=16
ARMOURmap[ARMOUR.PLATE]=18
ARMOURmap[ARMOUR.ROBE]=20
ARMOURmap[ARMOUR.CHAINMAIL]=22
export {ARMOURmap};
